spring:
  datasource:
    url: jdbc:tc:mysql:8.0.31:////orderbook?TC_REUSABLE=true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: "root"
    password: ""
  flyway:
    enabled: true
    default-schema: orderbook